const PG_PROCS_PART_1: &[ProcEntry] = &[
    // ── Type I/O functions ──
    ProcEntry {
        oid: 38,
        name: "int2in",
        nargs: 1,
        rettype: 21,
        argtypes: "2275",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 39,
        name: "int2out",
        nargs: 1,
        rettype: 2275,
        argtypes: "21",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 42,
        name: "int4in",
        nargs: 1,
        rettype: 23,
        argtypes: "2275",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 43,
        name: "int4out",
        nargs: 1,
        rettype: 2275,
        argtypes: "23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 46,
        name: "textin",
        nargs: 1,
        rettype: 25,
        argtypes: "2275",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 47,
        name: "textout",
        nargs: 1,
        rettype: 2275,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 56,
        name: "boollt",
        nargs: 2,
        rettype: 16,
        argtypes: "16 16",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 60,
        name: "booleq",
        nargs: 2,
        rettype: 16,
        argtypes: "16 16",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 65,
        name: "int4eq",
        nargs: 2,
        rettype: 16,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 66,
        name: "int4lt",
        nargs: 2,
        rettype: 16,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 67,
        name: "texteq",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 84,
        name: "boolne",
        nargs: 2,
        rettype: 16,
        argtypes: "16 16",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 141,
        name: "int4mul",
        nargs: 2,
        rettype: 23,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 144,
        name: "int4ne",
        nargs: 2,
        rettype: 16,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 147,
        name: "int4gt",
        nargs: 2,
        rettype: 16,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 149,
        name: "int4le",
        nargs: 2,
        rettype: 16,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 150,
        name: "int4ge",
        nargs: 2,
        rettype: 16,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 154,
        name: "int4div",
        nargs: 2,
        rettype: 23,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 156,
        name: "int4mod",
        nargs: 2,
        rettype: 23,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 157,
        name: "textne",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 177,
        name: "int4pl",
        nargs: 2,
        rettype: 23,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 181,
        name: "int4mi",
        nargs: 2,
        rettype: 23,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 212,
        name: "int4um",
        nargs: 1,
        rettype: 23,
        argtypes: "23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 213,
        name: "int4abs",
        nargs: 1,
        rettype: 23,
        argtypes: "23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── float8 operator functions ──
    ProcEntry {
        oid: 218,
        name: "float8pl",
        nargs: 2,
        rettype: 701,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 219,
        name: "float8mi",
        nargs: 2,
        rettype: 701,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 220,
        name: "float8um",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 221,
        name: "float8mul",
        nargs: 2,
        rettype: 701,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 287,
        name: "float4eq",
        nargs: 2,
        rettype: 16,
        argtypes: "700 700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 288,
        name: "float4ne",
        nargs: 2,
        rettype: 16,
        argtypes: "700 700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 289,
        name: "float4lt",
        nargs: 2,
        rettype: 16,
        argtypes: "700 700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 290,
        name: "float4le",
        nargs: 2,
        rettype: 16,
        argtypes: "700 700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 291,
        name: "float4gt",
        nargs: 2,
        rettype: 16,
        argtypes: "700 700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 292,
        name: "float4ge",
        nargs: 2,
        rettype: 16,
        argtypes: "700 700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 293,
        name: "float8eq",
        nargs: 2,
        rettype: 16,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 294,
        name: "float8ne",
        nargs: 2,
        rettype: 16,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 295,
        name: "float8lt",
        nargs: 2,
        rettype: 16,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 296,
        name: "float8le",
        nargs: 2,
        rettype: 16,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 297,
        name: "float8gt",
        nargs: 2,
        rettype: 16,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 298,
        name: "float8ge",
        nargs: 2,
        rettype: 16,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── bigint operator functions ──
    ProcEntry {
        oid: 462,
        name: "int8um",
        nargs: 1,
        rettype: 20,
        argtypes: "20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 463,
        name: "int8pl",
        nargs: 2,
        rettype: 20,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 464,
        name: "int8mi",
        nargs: 2,
        rettype: 20,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 465,
        name: "int8mul",
        nargs: 2,
        rettype: 20,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 466,
        name: "int8div",
        nargs: 2,
        rettype: 20,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 467,
        name: "int8eq",
        nargs: 2,
        rettype: 16,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 468,
        name: "int8ne",
        nargs: 2,
        rettype: 16,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 469,
        name: "int8lt",
        nargs: 2,
        rettype: 16,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 470,
        name: "int8gt",
        nargs: 2,
        rettype: 16,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 471,
        name: "int8le",
        nargs: 2,
        rettype: 16,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 472,
        name: "int8ge",
        nargs: 2,
        rettype: 16,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 947,
        name: "int8mod",
        nargs: 2,
        rettype: 20,
        argtypes: "20 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── text comparison functions ──
    ProcEntry {
        oid: 740,
        name: "text_lt",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 741,
        name: "text_le",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 742,
        name: "text_gt",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 743,
        name: "text_ge",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── text functions ──
    ProcEntry {
        oid: 870,
        name: "lower",
        nargs: 1,
        rettype: 25,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 871,
        name: "upper",
        nargs: 1,
        rettype: 25,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 877,
        name: "length",
        nargs: 1,
        rettype: 23,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 879,
        name: "lpad",
        nargs: 3,
        rettype: 25,
        argtypes: "25 23 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 880,
        name: "rpad",
        nargs: 3,
        rettype: 25,
        argtypes: "25 23 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 881,
        name: "ltrim",
        nargs: 1,
        rettype: 25,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 882,
        name: "rtrim",
        nargs: 1,
        rettype: 25,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 883,
        name: "substr",
        nargs: 3,
        rettype: 25,
        argtypes: "25 23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 884,
        name: "btrim",
        nargs: 1,
        rettype: 25,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 849,
        name: "position",
        nargs: 2,
        rettype: 23,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 850,
        name: "textlike",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 851,
        name: "textnlike",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1258,
        name: "textcat",
        nargs: 2,
        rettype: 25,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1620,
        name: "ascii",
        nargs: 1,
        rettype: 23,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1621,
        name: "chr",
        nargs: 1,
        rettype: 25,
        argtypes: "23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1622,
        name: "repeat",
        nargs: 2,
        rettype: 25,
        argtypes: "25 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1623,
        name: "replace",
        nargs: 3,
        rettype: 25,
        argtypes: "25 25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1624,
        name: "initcap",
        nargs: 1,
        rettype: 25,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1625,
        name: "left",
        nargs: 2,
        rettype: 25,
        argtypes: "25 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1626,
        name: "right",
        nargs: 2,
        rettype: 25,
        argtypes: "25 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1627,
        name: "reverse",
        nargs: 1,
        rettype: 25,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1633,
        name: "texticlike",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1634,
        name: "texticnlike",
        nargs: 2,
        rettype: 16,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 3058,
        name: "concat",
        nargs: 1,
        rettype: 25,
        argtypes: "2276",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 3059,
        name: "concat_ws",
        nargs: 2,
        rettype: 25,
        argtypes: "25 2276",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 3060,
        name: "left",
        nargs: 2,
        rettype: 25,
        argtypes: "25 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 3061,
        name: "right",
        nargs: 2,
        rettype: 25,
        argtypes: "25 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── math functions ──
    ProcEntry {
        oid: 1395,
        name: "abs",
        nargs: 1,
        rettype: 23,
        argtypes: "23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1340,
        name: "log",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1341,
        name: "ln",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1344,
        name: "exp",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1345,
        name: "sqrt",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1394,
        name: "round",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1342,
        name: "ceil",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1343,
        name: "floor",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1346,
        name: "power",
        nargs: 2,
        rettype: 701,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1347,
        name: "mod",
        nargs: 2,
        rettype: 23,
        argtypes: "23 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1598,
        name: "random",
        nargs: 0,
        rettype: 701,
        argtypes: "",
        prokind: "f",
        retset: false,
        volatility: "v",
    },
    ProcEntry {
        oid: 1600,
        name: "trunc",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1618,
        name: "sign",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1604,
        name: "pi",
        nargs: 0,
        rettype: 701,
        argtypes: "",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── trig functions ──
    ProcEntry {
        oid: 1606,
        name: "sin",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1607,
        name: "cos",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1608,
        name: "tan",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1609,
        name: "asin",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1610,
        name: "acos",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1611,
        name: "atan",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1612,
        name: "atan2",
        nargs: 2,
        rettype: 701,
        argtypes: "701 701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
];
