const PG_PROCS_PART_2: &[ProcEntry] = &[
    // ── datetime functions ──
    ProcEntry {
        oid: 1299,
        name: "now",
        nargs: 0,
        rettype: 1184,
        argtypes: "",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2020,
        name: "date_part",
        nargs: 2,
        rettype: 701,
        argtypes: "25 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2021,
        name: "date_trunc",
        nargs: 2,
        rettype: 1114,
        argtypes: "25 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2024,
        name: "age",
        nargs: 2,
        rettype: 1186,
        argtypes: "1114 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1770,
        name: "to_char",
        nargs: 2,
        rettype: 25,
        argtypes: "1114 25",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1773,
        name: "to_date",
        nargs: 2,
        rettype: 1082,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1774,
        name: "to_timestamp",
        nargs: 2,
        rettype: 1184,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1776,
        name: "to_number",
        nargs: 2,
        rettype: 1700,
        argtypes: "25 25",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2023,
        name: "extract",
        nargs: 2,
        rettype: 1700,
        argtypes: "25 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── date comparison functions ──
    ProcEntry {
        oid: 1086,
        name: "date_eq",
        nargs: 2,
        rettype: 16,
        argtypes: "1082 1082",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1087,
        name: "date_ne",
        nargs: 2,
        rettype: 16,
        argtypes: "1082 1082",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1088,
        name: "date_lt",
        nargs: 2,
        rettype: 16,
        argtypes: "1082 1082",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1089,
        name: "date_le",
        nargs: 2,
        rettype: 16,
        argtypes: "1082 1082",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1090,
        name: "date_gt",
        nargs: 2,
        rettype: 16,
        argtypes: "1082 1082",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1091,
        name: "date_ge",
        nargs: 2,
        rettype: 16,
        argtypes: "1082 1082",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1092,
        name: "date_mi",
        nargs: 2,
        rettype: 23,
        argtypes: "1082 1082",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── timestamp comparison functions ──
    ProcEntry {
        oid: 2052,
        name: "timestamp_eq",
        nargs: 2,
        rettype: 16,
        argtypes: "1114 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2053,
        name: "timestamp_ne",
        nargs: 2,
        rettype: 16,
        argtypes: "1114 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2054,
        name: "timestamp_lt",
        nargs: 2,
        rettype: 16,
        argtypes: "1114 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2055,
        name: "timestamp_le",
        nargs: 2,
        rettype: 16,
        argtypes: "1114 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2056,
        name: "timestamp_gt",
        nargs: 2,
        rettype: 16,
        argtypes: "1114 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2057,
        name: "timestamp_ge",
        nargs: 2,
        rettype: 16,
        argtypes: "1114 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2058,
        name: "timestamp_pl_interval",
        nargs: 2,
        rettype: 1114,
        argtypes: "1114 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2059,
        name: "timestamp_mi_interval",
        nargs: 2,
        rettype: 1114,
        argtypes: "1114 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2032,
        name: "timestamp_mi",
        nargs: 2,
        rettype: 1186,
        argtypes: "1114 1114",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2071,
        name: "date_pl_interval",
        nargs: 2,
        rettype: 1114,
        argtypes: "1082 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── timestamptz comparison functions ──
    ProcEntry {
        oid: 1152,
        name: "timestamptz_eq",
        nargs: 2,
        rettype: 16,
        argtypes: "1184 1184",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1153,
        name: "timestamptz_ne",
        nargs: 2,
        rettype: 16,
        argtypes: "1184 1184",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1154,
        name: "timestamptz_lt",
        nargs: 2,
        rettype: 16,
        argtypes: "1184 1184",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1155,
        name: "timestamptz_le",
        nargs: 2,
        rettype: 16,
        argtypes: "1184 1184",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1156,
        name: "timestamptz_gt",
        nargs: 2,
        rettype: 16,
        argtypes: "1184 1184",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1157,
        name: "timestamptz_ge",
        nargs: 2,
        rettype: 16,
        argtypes: "1184 1184",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1189,
        name: "timestamptz_pl_interval",
        nargs: 2,
        rettype: 1184,
        argtypes: "1184 1186",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1190,
        name: "timestamptz_mi_interval",
        nargs: 2,
        rettype: 1184,
        argtypes: "1184 1186",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    // ── interval comparison/arithmetic functions ──
    ProcEntry {
        oid: 1162,
        name: "interval_eq",
        nargs: 2,
        rettype: 16,
        argtypes: "1186 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1163,
        name: "interval_ne",
        nargs: 2,
        rettype: 16,
        argtypes: "1186 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1164,
        name: "interval_lt",
        nargs: 2,
        rettype: 16,
        argtypes: "1186 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1165,
        name: "interval_le",
        nargs: 2,
        rettype: 16,
        argtypes: "1186 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1166,
        name: "interval_gt",
        nargs: 2,
        rettype: 16,
        argtypes: "1186 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1167,
        name: "interval_ge",
        nargs: 2,
        rettype: 16,
        argtypes: "1186 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1169,
        name: "interval_pl",
        nargs: 2,
        rettype: 1186,
        argtypes: "1186 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1170,
        name: "interval_mi",
        nargs: 2,
        rettype: 1186,
        argtypes: "1186 1186",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── numeric comparison/arithmetic functions ──
    ProcEntry {
        oid: 1718,
        name: "numeric_eq",
        nargs: 2,
        rettype: 16,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1719,
        name: "numeric_ne",
        nargs: 2,
        rettype: 16,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1720,
        name: "numeric_gt",
        nargs: 2,
        rettype: 16,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1721,
        name: "numeric_ge",
        nargs: 2,
        rettype: 16,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1722,
        name: "numeric_lt",
        nargs: 2,
        rettype: 16,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1723,
        name: "numeric_le",
        nargs: 2,
        rettype: 16,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1724,
        name: "numeric_add",
        nargs: 2,
        rettype: 1700,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1725,
        name: "numeric_sub",
        nargs: 2,
        rettype: 1700,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1726,
        name: "numeric_mul",
        nargs: 2,
        rettype: 1700,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1727,
        name: "numeric_div",
        nargs: 2,
        rettype: 1700,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1728,
        name: "numeric_mod",
        nargs: 2,
        rettype: 1700,
        argtypes: "1700 1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1729,
        name: "numeric_uminus",
        nargs: 1,
        rettype: 1700,
        argtypes: "1700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── cross-type int4/int8 comparison functions ──
    ProcEntry {
        oid: 852,
        name: "int48eq",
        nargs: 2,
        rettype: 16,
        argtypes: "23 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 853,
        name: "int84eq",
        nargs: 2,
        rettype: 16,
        argtypes: "20 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 854,
        name: "int48ne",
        nargs: 2,
        rettype: 16,
        argtypes: "23 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 855,
        name: "int84ne",
        nargs: 2,
        rettype: 16,
        argtypes: "20 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 856,
        name: "int48lt",
        nargs: 2,
        rettype: 16,
        argtypes: "23 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 857,
        name: "int48gt",
        nargs: 2,
        rettype: 16,
        argtypes: "23 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 858,
        name: "int48le",
        nargs: 2,
        rettype: 16,
        argtypes: "23 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 859,
        name: "int48ge",
        nargs: 2,
        rettype: 16,
        argtypes: "23 20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 860,
        name: "int84lt",
        nargs: 2,
        rettype: 16,
        argtypes: "20 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 861,
        name: "int84gt",
        nargs: 2,
        rettype: 16,
        argtypes: "20 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 862,
        name: "int84le",
        nargs: 2,
        rettype: 16,
        argtypes: "20 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 863,
        name: "int84ge",
        nargs: 2,
        rettype: 16,
        argtypes: "20 23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── utility functions ──
    ProcEntry {
        oid: 1081,
        name: "format_type",
        nargs: 2,
        rettype: 25,
        argtypes: "26 23",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2304,
        name: "pg_typeof",
        nargs: 1,
        rettype: 2206,
        argtypes: "2276",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1191,
        name: "generate_series",
        nargs: 2,
        rettype: 23,
        argtypes: "23 23",
        prokind: "f",
        retset: true,
        volatility: "i",
    },
    ProcEntry {
        oid: 3100,
        name: "pg_get_viewdef",
        nargs: 1,
        rettype: 25,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1716,
        name: "pg_get_indexdef",
        nargs: 1,
        rettype: 25,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1642,
        name: "obj_description",
        nargs: 2,
        rettype: 25,
        argtypes: "26 19",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1643,
        name: "col_description",
        nargs: 2,
        rettype: 25,
        argtypes: "26 23",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1644,
        name: "shobj_description",
        nargs: 2,
        rettype: 25,
        argtypes: "26 19",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1716,
        name: "pg_get_constraintdef",
        nargs: 1,
        rettype: 25,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1665,
        name: "pg_get_expr",
        nargs: 2,
        rettype: 25,
        argtypes: "25 26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1402,
        name: "current_schema",
        nargs: 0,
        rettype: 19,
        argtypes: "",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 745,
        name: "current_user",
        nargs: 0,
        rettype: 19,
        argtypes: "",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    // ── JSONB functions ──
    ProcEntry {
        oid: 3204,
        name: "jsonb_typeof",
        nargs: 1,
        rettype: 25,
        argtypes: "3802",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 4048,
        name: "jsonb_contains",
        nargs: 2,
        rettype: 16,
        argtypes: "3802 3802",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 4049,
        name: "jsonb_contained",
        nargs: 2,
        rettype: 16,
        argtypes: "3802 3802",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── Cast functions ──
    ProcEntry {
        oid: 480,
        name: "int8",
        nargs: 1,
        rettype: 20,
        argtypes: "23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 481,
        name: "int4",
        nargs: 1,
        rettype: 23,
        argtypes: "20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 312,
        name: "float8",
        nargs: 1,
        rettype: 701,
        argtypes: "700",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 313,
        name: "float4",
        nargs: 1,
        rettype: 700,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 316,
        name: "float8",
        nargs: 1,
        rettype: 701,
        argtypes: "23",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 318,
        name: "float8",
        nargs: 1,
        rettype: 701,
        argtypes: "20",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 319,
        name: "int4",
        nargs: 1,
        rettype: 23,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 482,
        name: "int8",
        nargs: 1,
        rettype: 20,
        argtypes: "701",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    // ── Aggregate functions ──
    ProcEntry {
        oid: 2100,
        name: "avg",
        nargs: 1,
        rettype: 1700,
        argtypes: "20",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2101,
        name: "avg",
        nargs: 1,
        rettype: 1700,
        argtypes: "23",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2102,
        name: "avg",
        nargs: 1,
        rettype: 701,
        argtypes: "700",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2103,
        name: "avg",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2104,
        name: "avg",
        nargs: 1,
        rettype: 1700,
        argtypes: "1700",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2129,
        name: "min",
        nargs: 1,
        rettype: 23,
        argtypes: "23",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2130,
        name: "max",
        nargs: 1,
        rettype: 23,
        argtypes: "23",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2131,
        name: "min",
        nargs: 1,
        rettype: 20,
        argtypes: "20",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2132,
        name: "max",
        nargs: 1,
        rettype: 20,
        argtypes: "20",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2145,
        name: "count",
        nargs: 1,
        rettype: 20,
        argtypes: "2276",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2803,
        name: "count",
        nargs: 0,
        rettype: 20,
        argtypes: "",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2147,
        name: "sum",
        nargs: 1,
        rettype: 20,
        argtypes: "20",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2108,
        name: "sum",
        nargs: 1,
        rettype: 20,
        argtypes: "23",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2110,
        name: "sum",
        nargs: 1,
        rettype: 701,
        argtypes: "701",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 2114,
        name: "sum",
        nargs: 1,
        rettype: 1700,
        argtypes: "1700",
        prokind: "a",
        retset: false,
        volatility: "i",
    },
    // ── Coalesce / nullif ── (not in pg_proc in real PG, but harmless)
    ProcEntry {
        oid: 3530,
        name: "coalesce",
        nargs: 1,
        rettype: 2276,
        argtypes: "2276",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 3531,
        name: "nullif",
        nargs: 2,
        rettype: 2276,
        argtypes: "2276 2276",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 3532,
        name: "greatest",
        nargs: 1,
        rettype: 2276,
        argtypes: "2276",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 3533,
        name: "least",
        nargs: 1,
        rettype: 2276,
        argtypes: "2276",
        prokind: "f",
        retset: false,
        volatility: "i",
    },
    ProcEntry {
        oid: 1597,
        name: "pg_encoding_to_char",
        nargs: 1,
        rettype: 25,
        argtypes: "23",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 1598,
        name: "pg_char_to_encoding",
        nargs: 1,
        rettype: 23,
        argtypes: "25",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2080,
        name: "pg_table_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2081,
        name: "pg_function_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2092,
        name: "pg_proc_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2078,
        name: "pg_type_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2079,
        name: "pg_operator_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2082,
        name: "pg_opclass_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2083,
        name: "pg_opfamily_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2086,
        name: "pg_ts_dict_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2087,
        name: "pg_ts_config_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2088,
        name: "pg_ts_parser_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2089,
        name: "pg_ts_template_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2090,
        name: "pg_conversion_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2094,
        name: "pg_get_statisticsobjdef",
        nargs: 1,
        rettype: 25,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2095,
        name: "pg_get_statisticsobjdef_columns",
        nargs: 1,
        rettype: 25,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2096,
        name: "pg_get_functiondef",
        nargs: 1,
        rettype: 25,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2097,
        name: "pg_get_function_arguments",
        nargs: 1,
        rettype: 25,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2098,
        name: "pg_get_function_result",
        nargs: 1,
        rettype: 25,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2099,
        name: "pg_get_function_identity_arguments",
        nargs: 1,
        rettype: 25,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2084,
        name: "pg_collation_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
    ProcEntry {
        oid: 2085,
        name: "pg_statistics_obj_is_visible",
        nargs: 1,
        rettype: 16,
        argtypes: "26",
        prokind: "f",
        retset: false,
        volatility: "s",
    },
];
