"""
Extended SQLAlchemy ORM compatibility test.

Goes beyond the basic smoke test to verify the full introspection path
that ORMs use: columns, primary keys, foreign keys, indexes, unique
constraints, and basic CRUD via the ORM layer.
"""
import enum
import json
import os
import sys
import traceback
import warnings

from sqlalchemy import (
    Column,
    Enum,
    ForeignKey,
    Integer,
    MetaData,
    String,
    Table,
    UniqueConstraint,
    create_engine,
    inspect,
    text,
)
from sqlalchemy.orm import Session, DeclarativeBase, Mapped, mapped_column, relationship


# ── Schema setup via raw SQL ──────────────────────────────────────

SETUP_SQL = """
DROP TABLE IF EXISTS xtask_orm_posts;
DROP TABLE IF EXISTS xtask_orm_users;
DROP TABLE IF EXISTS xtask_orm_enum_probe;
DROP TABLE IF EXISTS dom.xtask_orm_domain_probe;
DROP TABLE IF EXISTS app.xtask_orm_enum_probe_app;
DROP DOMAIN IF EXISTS dom.xtask_orm_email_t;
DROP TYPE IF EXISTS xtask_orm_status_enum;
DROP TYPE IF EXISTS app.xtask_orm_status_enum_app;
DROP SCHEMA IF EXISTS dom CASCADE;
DROP SCHEMA IF EXISTS app CASCADE;

CREATE TABLE xtask_orm_users (
    id INT NOT NULL PRIMARY KEY,
    email TEXT NOT NULL,
    name TEXT
);

CREATE UNIQUE INDEX xtask_orm_users_email_idx ON xtask_orm_users (email);

CREATE TABLE xtask_orm_posts (
    id INT NOT NULL PRIMARY KEY,
    title TEXT NOT NULL,
    user_id INT NOT NULL REFERENCES xtask_orm_users(id)
);

CREATE INDEX xtask_orm_posts_user_id_idx ON xtask_orm_posts (user_id);

CREATE TYPE xtask_orm_status_enum AS ENUM ('draft', 'live', 'archived');

CREATE TABLE xtask_orm_enum_probe (
    id INT NOT NULL PRIMARY KEY,
    status xtask_orm_status_enum NOT NULL
);

CREATE SCHEMA dom;
CREATE DOMAIN dom.xtask_orm_email_t AS TEXT DEFAULT 'n/a' CHECK (POSITION('@' IN VALUE) > 1);
CREATE TABLE dom.xtask_orm_domain_probe (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email dom.xtask_orm_email_t NOT NULL,
    note TEXT DEFAULT 'x'
);

CREATE SCHEMA app;
CREATE TYPE app.xtask_orm_status_enum_app AS ENUM ('draft', 'live');
CREATE TABLE app.xtask_orm_parent_app (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status app.xtask_orm_status_enum_app NOT NULL
);
CREATE TABLE app.xtask_orm_child_app (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id INT NOT NULL REFERENCES app.xtask_orm_parent_app(id),
    slug TEXT NOT NULL UNIQUE
);
CREATE TABLE app.xtask_orm_grandchild_app (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id INT NOT NULL REFERENCES app.xtask_orm_child_app(id),
    note TEXT NOT NULL
);
CREATE TABLE app.xtask_orm_enum_probe_app (
    id INT NOT NULL PRIMARY KEY,
    status app.xtask_orm_status_enum_app NOT NULL
);
"""

TEARDOWN_SQL = """
DROP TABLE IF EXISTS app.xtask_orm_enum_probe_app;
DROP TYPE IF EXISTS app.xtask_orm_status_enum_app;
DROP SCHEMA IF EXISTS app CASCADE;
DROP TABLE IF EXISTS dom.xtask_orm_domain_probe;
DROP DOMAIN IF EXISTS dom.xtask_orm_email_t;
DROP SCHEMA IF EXISTS dom CASCADE;
DROP TABLE IF EXISTS xtask_orm_enum_probe;
DROP TYPE IF EXISTS xtask_orm_status_enum;
DROP TABLE IF EXISTS xtask_orm_posts;
DROP TABLE IF EXISTS xtask_orm_users;
"""


def run_checks(engine):
    results = {}

    # ── 1. Setup schema ──
    with engine.begin() as conn:
        for stmt in SETUP_SQL.strip().split(";"):
            stmt = stmt.strip()
            if stmt:
                conn.execute(text(stmt))
    results["setup"] = "ok"

    inspector = inspect(engine)

    # ── 2. Table discovery ──
    tables = inspector.get_table_names()
    assert "xtask_orm_users" in tables, f"users table not found in {tables}"
    assert "xtask_orm_posts" in tables, f"posts table not found in {tables}"
    assert "xtask_orm_parent_app" not in tables, f"non-public table leaked into visible tables: {tables}"
    assert "xtask_orm_child_app" not in tables, f"non-public table leaked into visible tables: {tables}"
    results["table_discovery"] = tables

    # ── 3. Column introspection ──
    user_cols = inspector.get_columns("xtask_orm_users")
    col_names = [c["name"] for c in user_cols]
    assert col_names == ["id", "email", "name"], f"unexpected columns: {col_names}"
    results["columns"] = col_names

    # ── 4. Primary key introspection ──
    pk = inspector.get_pk_constraint("xtask_orm_users")
    assert pk is not None, "no PK found"
    assert "id" in pk.get("constrained_columns", []), f"PK columns: {pk}"
    results["primary_key"] = pk

    # ── 5. Foreign key introspection ──
    fks = inspector.get_foreign_keys("xtask_orm_posts")
    assert len(fks) >= 1, f"expected at least 1 FK, got {fks}"
    fk = fks[0]
    assert fk["referred_table"] == "xtask_orm_users", f"FK refers to: {fk}"
    assert fk["referred_columns"] == ["id"], f"FK ref cols: {fk}"
    assert fk["constrained_columns"] == ["user_id"], f"FK cols: {fk}"
    results["foreign_keys"] = [
        {k: v for k, v in f.items() if k != "options"} for f in fks
    ]

    # ── 6. Index introspection ──
    indexes = inspector.get_indexes("xtask_orm_users")
    idx_names = [i["name"] for i in indexes]
    assert any("email" in n for n in idx_names), f"email index not found: {idx_names}"
    results["indexes"] = indexes

    # ── 7. Unique constraint introspection ──
    # (The UNIQUE INDEX should appear either here or as an index)
    try:
        uniques = inspector.get_unique_constraints("xtask_orm_users")
        results["unique_constraints"] = uniques
    except Exception as exc:
        results["unique_constraints"] = f"error: {exc}"

    # ── 8. MetaData.reflect() ──
    meta = MetaData()
    meta.reflect(bind=engine)
    reflected_tables = list(meta.tables.keys())
    assert "xtask_orm_users" in reflected_tables, f"reflect failed: {reflected_tables}"
    assert "xtask_orm_parent_app" not in reflected_tables, (
        f"non-public table reflected without schema: {reflected_tables}"
    )
    assert "app.xtask_orm_parent_app" not in reflected_tables, (
        f"non-public table reflected unexpectedly: {reflected_tables}"
    )
    results["metadata_reflect"] = reflected_tables

    # ── 9. Basic ORM CRUD ──
    class Base(DeclarativeBase):
        pass

    class User(Base):
        __tablename__ = "xtask_orm_users"
        id: Mapped[int] = mapped_column(primary_key=True)
        email: Mapped[str]
        name: Mapped[str | None]

    class Status(enum.Enum):
        DRAFT = "draft"
        LIVE = "live"
        ARCHIVED = "archived"

    class EnumProbe(Base):
        __tablename__ = "xtask_orm_enum_probe"
        id: Mapped[int] = mapped_column(primary_key=True)
        status: Mapped[Status] = mapped_column(
            Enum(
                Status,
                name="xtask_orm_status_enum",
                values_callable=lambda enum_cls: [member.value for member in enum_cls],
            )
        )

    class AppEnumProbe(Base):
        __tablename__ = "xtask_orm_enum_probe_app"
        __table_args__ = {"schema": "app"}
        id: Mapped[int] = mapped_column(primary_key=True)
        status: Mapped[Status] = mapped_column(
            Enum(
                Status,
                name="xtask_orm_status_enum_app",
                schema="app",
                values_callable=lambda enum_cls: [member.value for member in enum_cls],
            )
        )

    class AppParent(Base):
        __tablename__ = "xtask_orm_parent_app"
        __table_args__ = {"schema": "app"}
        id: Mapped[int] = mapped_column(primary_key=True)
        name: Mapped[str]
        status: Mapped[Status] = mapped_column(
            Enum(
                Status,
                name="xtask_orm_status_enum_app",
                schema="app",
                values_callable=lambda enum_cls: [member.value for member in enum_cls],
            )
        )
        children: Mapped[list["AppChild"]] = relationship(
            back_populates="parent", cascade="all, delete-orphan"
        )

    class AppChild(Base):
        __tablename__ = "xtask_orm_child_app"
        __table_args__ = {"schema": "app"}
        id: Mapped[int] = mapped_column(primary_key=True)
        parent_id: Mapped[int] = mapped_column(ForeignKey("app.xtask_orm_parent_app.id"))
        slug: Mapped[str]
        parent: Mapped[AppParent] = relationship(back_populates="children")
        grandchildren: Mapped[list["AppGrandchild"]] = relationship(
            back_populates="child", cascade="all, delete-orphan"
        )

    class AppGrandchild(Base):
        __tablename__ = "xtask_orm_grandchild_app"
        __table_args__ = {"schema": "app"}
        id: Mapped[int] = mapped_column(primary_key=True)
        child_id: Mapped[int] = mapped_column(ForeignKey("app.xtask_orm_child_app.id"))
        note: Mapped[str]
        child: Mapped[AppChild] = relationship(back_populates="grandchildren")

    enums = inspector.get_enums(schema="public")
    enum_names = [enum_def["name"] for enum_def in enums]
    assert "xtask_orm_status_enum" in enum_names, f"enum not found: {enums}"
    results["enums"] = enums

    enum_cols = inspector.get_columns("xtask_orm_enum_probe")
    status_col = next((col for col in enum_cols if col["name"] == "status"), None)
    assert status_col is not None, f"status column missing: {enum_cols}"
    status_type = status_col["type"]
    assert hasattr(status_type, "enums"), f"status type is not native enum: {status_type!r}"
    assert list(status_type.enums) == ["draft", "live", "archived"], (
        f"unexpected enum labels: {status_type!r}"
    )
    results["enum_columns"] = [
        {
            "name": col["name"],
            "type": str(col["type"]),
        }
        for col in enum_cols
    ]

    app_enums = inspector.get_enums(schema="app")
    app_enum = next(
        (enum_def for enum_def in app_enums if enum_def["name"] == "xtask_orm_status_enum_app"),
        None,
    )
    assert app_enum is not None, f"app enum not found: {app_enums}"
    assert app_enum["schema"] == "app", f"unexpected app enum schema: {app_enum}"
    assert app_enum["visible"] is False, f"unexpected app enum visibility: {app_enum}"
    assert app_enum["labels"] == ["draft", "live"], f"unexpected app enum labels: {app_enum}"
    results["app_enums"] = app_enums

    app_enum_cols = inspector.get_columns("xtask_orm_enum_probe_app", schema="app")
    app_status_col = next((col for col in app_enum_cols if col["name"] == "status"), None)
    assert app_status_col is not None, f"app status column missing: {app_enum_cols}"
    app_status_type = app_status_col["type"]
    assert hasattr(app_status_type, "enums"), (
        f"app status type is not native enum: {app_status_type!r}"
    )
    assert app_status_type.schema == "app", f"unexpected app enum schema: {app_status_type!r}"
    assert list(app_status_type.enums) == ["draft", "live"], (
        f"unexpected app enum labels: {app_status_type!r}"
    )
    results["app_enum_columns"] = [
        {
            "name": col["name"],
            "type": str(col["type"]),
        }
        for col in app_enum_cols
    ]

    domains = inspector.get_domains(schema="dom")
    domain = next((entry for entry in domains if entry["name"] == "xtask_orm_email_t"), None)
    assert domain is not None, f"domain not found: {domains}"
    assert domain["schema"] == "dom", f"unexpected domain schema: {domain}"
    assert domain["visible"] is False, f"unexpected domain visibility: {domain}"
    assert domain["nullable"] is True, f"unexpected domain nullability: {domain}"
    assert domain["default"] == "'n/a'", f"unexpected domain default: {domain}"
    assert any("POSITION('@' IN VALUE) > 1" in constraint["check"] for constraint in domain["constraints"]), (
        f"unexpected domain constraints: {domain}"
    )
    results["domains"] = domains

    domain_cols = inspector.get_columns("xtask_orm_domain_probe", schema="dom")
    email_col = next((col for col in domain_cols if col["name"] == "email"), None)
    assert email_col is not None, f"domain email column missing: {domain_cols}"
    assert email_col["type"].__class__.__name__.lower() == "domain", (
        f"domain column type not reflected as DOMAIN: {email_col!r}"
    )
    assert getattr(email_col["type"], "name", None) == "xtask_orm_email_t", (
        f"unexpected domain type name: {email_col['type']!r}"
    )
    assert getattr(email_col["type"], "schema", None) == "dom", (
        f"unexpected domain type schema: {email_col['type']!r}"
    )
    results["domain_columns"] = [
        {
            "name": col["name"],
            "type": str(col["type"]),
            "default": col.get("default"),
        }
        for col in domain_cols
    ]

    with warnings.catch_warnings(record=True) as caught_warnings:
        warnings.simplefilter("always")
        domain_table = Table(
            "xtask_orm_domain_probe",
            MetaData(),
            schema="dom",
            autoload_with=engine,
        )
    assert not any(
        "Did not recognize type 'xtask_orm_email_t'" in str(item.message)
        for item in caught_warnings
    ), f"domain autoload warnings: {[str(item.message) for item in caught_warnings]}"
    assert domain_table.c.email.type.__class__.__name__.lower() == "domain", (
        f"autoloaded domain type not preserved: {domain_table.c.email.type!r}"
    )
    results["domain_autoload"] = {
        "columns": [column.name for column in domain_table.columns],
        "email_type": str(domain_table.c.email.type),
    }

    app_parent_cols = inspector.get_columns("xtask_orm_parent_app", schema="app")
    app_parent_id_col = next((col for col in app_parent_cols if col["name"] == "id"), None)
    assert app_parent_id_col is not None, f"app parent id column missing: {app_parent_cols}"
    app_parent_default = app_parent_id_col.get("default")
    assert app_parent_default and "app.xtask_orm_parent_app_id_seq" in app_parent_default, (
        f"unexpected app parent identity default: {app_parent_id_col}"
    )
    results["app_identity_columns"] = [
        {
            "name": col["name"],
            "default": col.get("default"),
            "autoincrement": col.get("autoincrement"),
        }
        for col in app_parent_cols
    ]

    with Session(engine) as session:
        session.execute(
            text("INSERT INTO xtask_orm_users (id, email, name) VALUES (1, 'alice@test.com', 'Alice')")
        )
        session.add(EnumProbe(id=1, status=Status.LIVE))
        session.add(AppEnumProbe(id=1, status=Status.LIVE))
        session.commit()

        user = session.query(User).filter_by(email="alice@test.com").first()
        assert user is not None, "ORM query returned None"
        assert user.name == "Alice", f"expected Alice, got {user.name}"
        results["orm_query"] = {"id": user.id, "email": user.email, "name": user.name}

        enum_row = session.query(EnumProbe).filter_by(id=1).first()
        assert enum_row is not None, "enum ORM query returned None"
        assert enum_row.status is Status.LIVE, f"expected Status.LIVE, got {enum_row.status}"
        results["enum_orm_query"] = {
            "id": enum_row.id,
            "status": enum_row.status.value,
        }

        app_enum_row = session.query(AppEnumProbe).filter_by(id=1).first()
        assert app_enum_row is not None, "schema app enum ORM query returned None"
        assert app_enum_row.status is Status.LIVE, (
            f"expected Status.LIVE, got {app_enum_row.status}"
        )
        results["app_enum_orm_query"] = {
            "id": app_enum_row.id,
            "status": app_enum_row.status.value,
        }

        app_parent = AppParent(name="alice app", status=Status.LIVE)
        app_child = AppChild(slug="app-child-1")
        app_child.grandchildren.append(AppGrandchild(note="note-1"))
        app_parent.children.append(app_child)
        session.add(app_parent)
        session.commit()

        assert app_parent.id == 1, f"unexpected app parent id: {app_parent.id}"
        assert app_child.id == 1, f"unexpected app child id: {app_child.id}"
        assert app_child.grandchildren[0].id == 1, (
            f"unexpected app grandchild id: {app_child.grandchildren[0].id}"
        )
        results["app_identity_orm"] = {
            "parent_id": app_parent.id,
            "child_id": app_child.id,
            "grandchild_id": app_child.grandchildren[0].id,
        }

    # ── Teardown ──
    with engine.begin() as conn:
        for stmt in TEARDOWN_SQL.strip().split(";"):
            stmt = stmt.strip()
            if stmt:
                conn.execute(text(stmt))

    return results


def main():
    url = os.environ.get("SQLALCHEMY_DATABASE_URL")
    if not url:
        print("SQLALCHEMY_DATABASE_URL not set", file=sys.stderr)
        sys.exit(1)

    engine = create_engine(url, future=True)
    try:
        results = run_checks(engine)
        print(json.dumps({"status": "pass", "checks": results}, indent=2))
    except Exception as exc:
        traceback.print_exc(file=sys.stderr)
        print(json.dumps({"status": "fail", "error": str(exc)}))
        sys.exit(1)
    finally:
        engine.dispose()


if __name__ == "__main__":
    main()
