use super::Keyword;

pub fn lookup_keyword(input: &str) -> Option<Keyword> {
    // All current SQL/Cypher keywords are ASCII and 2..=15 bytes.
    const MIN_KEYWORD_LEN: usize = 2;
    const MAX_KEYWORD_LEN: usize = 15;
    let len = input.len();
    if !(MIN_KEYWORD_LEN..=MAX_KEYWORD_LEN).contains(&len) {
        return None;
    }

    if input.is_ascii() {
        let bytes = input.as_bytes();
        let mut first_lower = None;
        for (idx, byte) in bytes.iter().enumerate() {
            if byte.is_ascii_lowercase() {
                first_lower = Some(idx);
                break;
            }
        }

        // Already uppercase ASCII: avoid any copying.
        let Some(first_lower) = first_lower else {
            return lookup_keyword_inner(input);
        };

        // Uppercase into stack storage to avoid heap allocation.
        let mut buf = [0u8; MAX_KEYWORD_LEN];
        if first_lower > 0 {
            buf[..first_lower].copy_from_slice(&bytes[..first_lower]);
        }
        for (dst, src) in buf[first_lower..len]
            .iter_mut()
            .zip(bytes[first_lower..].iter())
        {
            *dst = src.to_ascii_uppercase();
        }
        let Ok(upper) = std::str::from_utf8(&buf[..len]) else {
            return None;
        };
        return lookup_keyword_inner(upper);
    }

    // SQL/Cypher keywords in this parser are ASCII-only.
    None
}

fn lookup_keyword_inner(input: &str) -> Option<Keyword> {
    match input {
        "ADD" => Some(Keyword::Add),
        "ANALYZE" => Some(Keyword::Analyze),
        "ALTER" => Some(Keyword::Alter),
        "ARRAY" => Some(Keyword::Array),
        "AND" => Some(Keyword::And),
        "ASC" => Some(Keyword::Asc),
        "AS" => Some(Keyword::As),
        "BACKUP" => Some(Keyword::Backup),
        "BETWEEN" => Some(Keyword::Between),
        "BIGINT" => Some(Keyword::BigInt),
        "BEGIN" => Some(Keyword::Begin),
        "BLOB" => Some(Keyword::Blob),
        "BY" => Some(Keyword::By),
        "CASE" => Some(Keyword::Case),
        "CAST" => Some(Keyword::Cast),
        "COLUMN" => Some(Keyword::Column),
        "COPY" => Some(Keyword::Copy),
        "DELETE" => Some(Keyword::Delete),
        "DEFAULT" => Some(Keyword::Default),
        "DESC" => Some(Keyword::Desc),
        "DISTINCT" => Some(Keyword::Distinct),
        "DO" => Some(Keyword::Do),
        "COMMITTED" => Some(Keyword::Committed),
        "COMMIT" => Some(Keyword::Commit),
        "CONFLICT" => Some(Keyword::Conflict),
        "CREATE" => Some(Keyword::Create),
        "DATABASE" => Some(Keyword::Database),
        "DATE" => Some(Keyword::Date),
        "DECIMAL" => Some(Keyword::Decimal),
        "BOOLEAN" => Some(Keyword::Boolean),
        "DOUBLE" => Some(Keyword::Double),
        "DROP" => Some(Keyword::Drop),
        "ELSE" => Some(Keyword::Else),
        "END" => Some(Keyword::End),
        "FALSE" => Some(Keyword::False),
        "FILTER" => Some(Keyword::Filter),
        "FROM" => Some(Keyword::From),
        "GROUP" => Some(Keyword::Group),
        "HAVING" => Some(Keyword::Having),
        "IF" => Some(Keyword::If),
        "ILIKE" => Some(Keyword::Ilike),
        "IN" => Some(Keyword::In),
        "INDEX" => Some(Keyword::Index),
        "INT" => Some(Keyword::Int),
        "INTERVAL" => Some(Keyword::Interval),
        "INSERT" => Some(Keyword::Insert),
        "IS" => Some(Keyword::Is),
        "ISOLATION" => Some(Keyword::Isolation),
        "INTO" => Some(Keyword::Into),
        "LIKE" => Some(Keyword::Like),
        "LIMIT" => Some(Keyword::Limit),
        "LEVEL" => Some(Keyword::Level),
        "NUMERIC" => Some(Keyword::Numeric),
        "NOT" => Some(Keyword::Not),
        "NULL" => Some(Keyword::Null),
        "ON" => Some(Keyword::On),
        "ORDER" => Some(Keyword::Order),
        "READ" => Some(Keyword::Read),
        "REAL" => Some(Keyword::Real),
        "RESTORE" => Some(Keyword::Restore),
        "ROLLBACK" => Some(Keyword::Rollback),
        "SEQUENCE" => Some(Keyword::Sequence),
        "SELECT" => Some(Keyword::Select),
        "SET" => Some(Keyword::Set),
        "SNAPSHOT" => Some(Keyword::Snapshot),
        "START" => Some(Keyword::Start),
        "STDIN" => Some(Keyword::Stdin),
        "STDOUT" => Some(Keyword::Stdout),
        "OR" => Some(Keyword::Or),
        "TABLE" => Some(Keyword::Table),
        "TEXT" => Some(Keyword::Text),
        "THEN" => Some(Keyword::Then),
        "TIME" => Some(Keyword::Time),
        "TIMESTAMP" => Some(Keyword::Timestamp),
        "TRANSACTION" => Some(Keyword::Transaction),
        "TRUE" => Some(Keyword::True),
        "UPDATE" => Some(Keyword::Update),
        "VALUES" => Some(Keyword::Values),
        "WHEN" => Some(Keyword::When),
        "WHERE" => Some(Keyword::Where),
        "OFFSET" => Some(Keyword::Offset),
        "COALESCE" => Some(Keyword::Coalesce),
        "CROSS" => Some(Keyword::Cross),
        "FULL" => Some(Keyword::Full),
        "INNER" => Some(Keyword::Inner),
        "JOIN" => Some(Keyword::Join),
        "JSONB" => Some(Keyword::Jsonb),
        "LEFT" => Some(Keyword::Left),
        "NULLIF" => Some(Keyword::Nullif),
        "OUTER" => Some(Keyword::Outer),
        "RIGHT" => Some(Keyword::Right),
        "UNION" => Some(Keyword::Union),
        "INTERSECT" => Some(Keyword::Intersect),
        "EXCEPT" => Some(Keyword::Except),
        "EXISTS" => Some(Keyword::Exists),
        "ALL" => Some(Keyword::All),
        "CHECK" => Some(Keyword::Check),
        "CONSTRAINT" => Some(Keyword::Constraint),
        "EXPLAIN" => Some(Keyword::Explain),
        "FOREIGN" => Some(Keyword::Foreign),
        "KEY" => Some(Keyword::Key),
        "PRIMARY" => Some(Keyword::Primary),
        "REFERENCES" => Some(Keyword::References),
        "RELEASE" => Some(Keyword::Release),
        "RENAME" => Some(Keyword::Rename),
        "REPLACE" => Some(Keyword::Replace),
        "SAVEPOINT" => Some(Keyword::Savepoint),
        "TIMESTAMPTZ" => Some(Keyword::Timestamptz),
        "TO" => Some(Keyword::To),
        "UNIQUE" => Some(Keyword::Unique),
        "UUID" => Some(Keyword::Uuid),
        "VACUUM" => Some(Keyword::Vacuum),
        "VECTOR" => Some(Keyword::Vector),
        "VIEW" => Some(Keyword::View),
        "NODE" => Some(Keyword::Node),
        "EDGE" => Some(Keyword::Edge),
        "LABEL" => Some(Keyword::Label),
        "SOURCE" => Some(Keyword::Source),
        "TARGET" => Some(Keyword::Target),
        "TENANT" => Some(Keyword::Tenant),
        "GRANT" => Some(Keyword::Grant),
        "REVOKE" => Some(Keyword::Revoke),
        "ROLE" => Some(Keyword::Role),
        "LOGIN" => Some(Keyword::Login),
        "PASSWORD" => Some(Keyword::Password),
        "SUPERUSER" => Some(Keyword::Superuser),
        "NOSUPERUSER" => Some(Keyword::Nosuperuser),
        "NOLOGIN" => Some(Keyword::Nologin),
        "NOTHING" => Some(Keyword::Nothing),
        "OVER" => Some(Keyword::Over),
        "PARTITION" => Some(Keyword::Partition),
        "PRIVILEGES" => Some(Keyword::Privileges),
        "SCHEMA" => Some(Keyword::Schema),
        "STATISTICS" => Some(Keyword::Statistics),
        "USING" => Some(Keyword::Using),
        "WITH" => Some(Keyword::With),
        "FUNCTION" => Some(Keyword::Function),
        "LANGUAGE" => Some(Keyword::Language),
        "RETURNS" => Some(Keyword::Returns),
        "TRIGGER" => Some(Keyword::Trigger),
        "BEFORE" => Some(Keyword::Before),
        "AFTER" => Some(Keyword::After),
        "EXECUTE" => Some(Keyword::Execute),
        "EACH" => Some(Keyword::Each),
        "ROW" => Some(Keyword::Row),
        "PROCEDURE" => Some(Keyword::Procedure),
        "TRUNCATE" => Some(Keyword::Truncate),
        "RETURNING" => Some(Keyword::Returning),
        "TYPE" => Some(Keyword::Type),
        "DATA" => Some(Keyword::Data),
        "SHOW" => Some(Keyword::Show),
        "RESET" => Some(Keyword::Reset),
        "ZONE" => Some(Keyword::Zone),
        "CASCADE" => Some(Keyword::Cascade),
        "COMMENT" => Some(Keyword::Comment),
        "DISCARD" => Some(Keyword::Discard),
        "EXCLUDE" => Some(Keyword::Exclude),
        "FETCH" => Some(Keyword::Fetch),
        "FIRST" => Some(Keyword::First),
        "FOLLOWING" => Some(Keyword::Following),
        "GROUPS" => Some(Keyword::Groups),
        "AGGREGATE" => Some(Keyword::Aggregate),
        "DOMAIN" => Some(Keyword::Domain),
        "LAST" => Some(Keyword::Last),
        "LOCK" => Some(Keyword::Lock),
        "NEXT" => Some(Keyword::Next),
        "OPERATOR" => Some(Keyword::Operator),
        "NULLS" => Some(Keyword::Nulls),
        "PRECEDING" => Some(Keyword::Preceding),
        "RANGE" => Some(Keyword::Range),
        "REINDEX" => Some(Keyword::Reindex),
        "ROWS" => Some(Keyword::Rows),
        "UNBOUNDED" => Some(Keyword::Unbounded),
        "WITHIN" => Some(Keyword::Within),
        "BOOL" => Some(Keyword::Bool),
        "BYTEA" => Some(Keyword::Bytea),
        "CHAR" => Some(Keyword::Char),
        "CHARACTER" => Some(Keyword::Character),
        "FLOAT" => Some(Keyword::Float),
        "FLOAT4" => Some(Keyword::Float4),
        "FLOAT8" => Some(Keyword::Float8),
        "INT2" => Some(Keyword::Int2),
        "INT4" => Some(Keyword::Int4),
        "INT8" => Some(Keyword::Int8),
        "INTEGER" => Some(Keyword::Integer),
        "SERIAL" => Some(Keyword::Serial),
        "BIGSERIAL" => Some(Keyword::BigSerial),
        "SMALLINT" => Some(Keyword::SmallInt),
        "VARCHAR" => Some(Keyword::Varchar),
        "VARYING" => Some(Keyword::Varying),
        "PRECISION" => Some(Keyword::Precision),
        "TEMPORARY" => Some(Keyword::Temporary),
        "TEMP" => Some(Keyword::Temp),
        "LOCAL" => Some(Keyword::Local),
        "GLOBAL" => Some(Keyword::Global),
        "ONLY" => Some(Keyword::Only),
        "LATERAL" => Some(Keyword::Lateral),
        "NATURAL" => Some(Keyword::Natural),
        "ANY" => Some(Keyword::Any),
        "SOME" => Some(Keyword::Some),
        "FOR" => Some(Keyword::For),
        "NO" => Some(Keyword::No),
        "ACTION" => Some(Keyword::Action),
        "RESTRICT" => Some(Keyword::Restrict),
        "RECURSIVE" => Some(Keyword::Recursive),
        "MATERIALIZED" => Some(Keyword::Materialized),
        "REFRESH" => Some(Keyword::Refresh),
        "CONCURRENTLY" => Some(Keyword::Concurrently),
        "WITHOUT" => Some(Keyword::Without),
        "OIDS" => Some(Keyword::Oids),
        "INHERIT" => Some(Keyword::Inherit),
        "INHERITS" => Some(Keyword::Inherits),
        "OF" => Some(Keyword::Of),
        "OWNED" => Some(Keyword::Owned),
        "OWNER" => Some(Keyword::Owner),
        "UNLOGGED" => Some(Keyword::Unlogged),
        "LOGGED" => Some(Keyword::Logged),
        "WORK" => Some(Keyword::Work),
        "CHAIN" => Some(Keyword::Chain),
        "DEFERRABLE" => Some(Keyword::Deferrable),
        "DEFERRED" => Some(Keyword::Deferred),
        "IMMEDIATE" => Some(Keyword::Immediate),
        "INITIALLY" => Some(Keyword::Initially),
        "ENABLE" => Some(Keyword::Enable),
        "DISABLE" => Some(Keyword::Disable),
        "REPLICA" => Some(Keyword::Replica),
        "ALWAYS" => Some(Keyword::Always),
        "IDENTITY" => Some(Keyword::Identity),
        "GENERATED" => Some(Keyword::Generated),
        "STORED" => Some(Keyword::Stored),
        "INCREMENT" => Some(Keyword::Increment),
        "MINVALUE" => Some(Keyword::Minvalue),
        "MAXVALUE" => Some(Keyword::Maxvalue),
        "CYCLE" => Some(Keyword::Cycle),
        "CACHE" => Some(Keyword::Cache),
        "OVERRIDING" => Some(Keyword::Overriding),
        "SYSTEM" => Some(Keyword::System),
        "USER" => Some(Keyword::User),
        "VALUE" => Some(Keyword::Value),
        "CURRENT" => Some(Keyword::Current),
        "SESSION" => Some(Keyword::Session),
        "AUTHORIZATION" => Some(Keyword::Authorization),
        "NONE" => Some(Keyword::None),
        "SETOF" => Some(Keyword::Setof),
        "BIT" => Some(Keyword::Bit),
        "TIMETZ" => Some(Keyword::Timetz),
        "MERGE" => Some(Keyword::Merge),
        "MATCHED" => Some(Keyword::Matched),
        "MATCH" => Some(Keyword::Match),
        "RETURN" => Some(Keyword::Return),
        "OPTIONAL" => Some(Keyword::Optional),
        "DETACH" => Some(Keyword::Detach),
        "UNWIND" => Some(Keyword::Unwind),
        "REMOVE" => Some(Keyword::Remove),
        "YIELD" => Some(Keyword::Yield),
        "SKIP" => Some(Keyword::Skip),
        "CALL" => Some(Keyword::Call),
        "FOREACH" => Some(Keyword::Foreach),
        "PROFILE" => Some(Keyword::Profile),
        "FIELDTERMINATOR" => Some(Keyword::FieldTerminator),
        "HEADERS" => Some(Keyword::Headers),
        "PERIODIC" => Some(Keyword::Periodic),
        "LOAD" => Some(Keyword::Load),
        "CSV" => Some(Keyword::Csv),
        _ => None,
    }
}
