#![allow(clippy::pedantic)]

use super::*;

#[path = "arrays_builtins.rs"]
mod builtins;
#[path = "arrays_indexing_and_slices.rs"]
mod indexing_and_slices;

// ===================================================================
// CREATE TABLE with array columns
// ===================================================================

#[test]
fn create_table_with_int_array_column() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (id INT NOT NULL, tags INT[])")
        .expect("create table with int array");
}

#[test]
fn create_table_with_text_array_column() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (id INT NOT NULL, names TEXT[])")
        .expect("create table with text array");
}

#[test]
fn unnest_with_ordinality_in_from_clause_returns_positions() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "SELECT colid, arridx FROM unnest(ARRAY[10,20]) WITH ORDINALITY AS cols(colid, arridx)",
    );
    assert_eq!(rows.len(), 2);
    assert_eq!(rows[0].values[0], Value::Int(10));
    assert!(matches!(
        rows[0].values[1],
        Value::BigInt(1) | Value::Int(1)
    ));
    assert_eq!(rows[1].values[0], Value::Int(20));
    assert!(matches!(
        rows[1].values[1],
        Value::BigInt(2) | Value::Int(2)
    ));
}

#[test]
fn unnest_with_ordinality_supports_correlated_pg_catalog_arrays() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE django_probe_composite ( \
                 a INT NOT NULL, \
                 b INT NOT NULL, \
                 CONSTRAINT django_probe_composite_pkey PRIMARY KEY (a, b) \
             )",
        )
        .expect("create probe table");

    let rows = query_rows(
        &engine,
        &session,
        "SELECT c.conname, \
                (SELECT count(*) \
                   FROM unnest(c.conkey) WITH ORDINALITY AS cols(colid, arridx)) \
         FROM pg_catalog.pg_constraint c \
         JOIN pg_catalog.pg_class cl ON c.conrelid = cl.oid \
         WHERE cl.relname = 'django_probe_composite' \
         ORDER BY 1",
    );
    assert_eq!(rows.len(), 1);
    assert_eq!(
        rows[0].values,
        vec![
            Value::Text("django_probe_composite_pkey".to_owned()),
            Value::BigInt(2),
        ]
    );
}

#[test]
fn insert_select_from_multi_array_unnest_returning_rows() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE django_content_type ( \
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
                 app_label VARCHAR(100) NOT NULL, \
                 model VARCHAR(100) NOT NULL \
             )",
        )
        .expect("create content type table");

    let results = engine
        .execute_sql(
            &session,
            "INSERT INTO django_content_type (app_label, model) \
             SELECT * \
             FROM UNNEST( \
                 ARRAY['xtask_django_app', 'xtask_django_app']::varchar[], \
                 ARRAY['post', 'user']::varchar[] \
             ) \
             RETURNING id, app_label, model",
        )
        .expect("insert from multi-array unnest");
    let [StatementResult::Query { rows, .. }] = results.as_slice() else {
        panic!("expected returning rows, got {results:?}");
    };
    assert_eq!(rows.len(), 2);
    assert_eq!(
        rows[0].values[1],
        Value::Text("xtask_django_app".to_owned())
    );
    assert_eq!(rows[0].values[2], Value::Text("post".to_owned()));
    assert_eq!(
        rows[1].values[1],
        Value::Text("xtask_django_app".to_owned())
    );
    assert_eq!(rows[1].values[2], Value::Text("user".to_owned()));
}

#[test]
fn composite_unique_prefix_filter_returns_all_matching_rows() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE django_content_type ( \
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
                 app_label VARCHAR(100) NOT NULL, \
                 model VARCHAR(100) NOT NULL, \
                 CONSTRAINT django_content_type_app_label_model_key UNIQUE (app_label, model) \
             ); \
             INSERT INTO django_content_type (app_label, model) VALUES \
                 ('xtask_django_app', 'post'), \
                 ('xtask_django_app', 'user'), \
                 ('other_app', 'post')",
        )
        .expect("setup composite unique probe");

    let access_path = access_path_for_query(
        &engine,
        &session,
        "SELECT model \
         FROM django_content_type \
         WHERE app_label = 'xtask_django_app' \
         ORDER BY model",
    );
    let composite_prefix_scan = match &access_path {
        aiondb_plan::ScanAccessPath::IndexEqComposite { .. } => true,
        aiondb_plan::ScanAccessPath::IndexOnlyScan { inner, .. } => matches!(
            inner.as_ref(),
            aiondb_plan::ScanAccessPath::IndexEqComposite { .. }
        ),
        _ => false,
    };
    assert!(
        composite_prefix_scan,
        "unexpected access path for composite-prefix equality: {access_path:?}"
    );

    let rows = query_rows(
        &engine,
        &session,
        "SELECT model \
         FROM django_content_type \
         WHERE app_label = 'xtask_django_app' \
         ORDER BY model",
    );
    assert_eq!(
        rows,
        vec![
            Row::new(vec![Value::Text("post".to_owned())]),
            Row::new(vec![Value::Text("user".to_owned())]),
        ]
    );
}

#[test]
fn unnest_multi_array_with_ordinality_in_from_clause_returns_zipped_rows() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "SELECT a, b, ord \
         FROM unnest(ARRAY[10,20], ARRAY[100,200]) WITH ORDINALITY AS u(a, b, ord)",
    );
    assert_eq!(rows.len(), 2);
    assert_eq!(rows[0].values[0], Value::Int(10));
    assert_eq!(rows[0].values[1], Value::Int(100));
    assert!(matches!(
        rows[0].values[2],
        Value::BigInt(1) | Value::Int(1)
    ));
    assert_eq!(rows[1].values[0], Value::Int(20));
    assert_eq!(rows[1].values[1], Value::Int(200));
    assert!(matches!(
        rows[1].values[2],
        Value::BigInt(2) | Value::Int(2)
    ));
}

#[test]
fn temp_table_shadows_public_table_with_same_name() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE public.shadow_me (id INT)")
        .expect("create public table");
    engine
        .execute_sql(&session, "INSERT INTO public.shadow_me VALUES (1)")
        .expect("insert public row");
    engine
        .execute_sql(&session, "CREATE TEMP TABLE shadow_me AS SELECT 2 AS id")
        .expect("create temp shadow");

    let temp_rows = query_rows(&engine, &session, "SELECT id FROM shadow_me");
    assert_eq!(temp_rows.len(), 1);
    assert_eq!(temp_rows[0].values[0], Value::Int(2));

    let public_rows = query_rows(&engine, &session, "SELECT id FROM public.shadow_me");
    assert_eq!(public_rows.len(), 1);
    assert_eq!(public_rows[0].values[0], Value::Int(1));
}

// ===================================================================
// INSERT with ARRAY literals
// ===================================================================

#[test]
fn insert_int_array_literal() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (id INT NOT NULL, vals INT[])")
        .expect("create table");

    engine
        .execute_sql(&session, "INSERT INTO t VALUES (1, ARRAY[10, 20, 30])")
        .expect("insert array");

    let results = engine
        .execute_sql(&session, "SELECT vals FROM t WHERE id = 1")
        .expect("select");

    match &results[0] {
        StatementResult::Query { rows, .. } => {
            assert_eq!(rows.len(), 1);
            assert_eq!(
                rows[0].values[0],
                Value::Array(vec![Value::Int(10), Value::Int(20), Value::Int(30)])
            );
        }
        other => panic!("expected query, got {other:?}"),
    }
}

#[test]
fn insert_text_array_literal() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (id INT NOT NULL, tags TEXT[])")
        .expect("create table");

    engine
        .execute_sql(
            &session,
            "INSERT INTO t VALUES (1, ARRAY['hello', 'world'])",
        )
        .expect("insert text array");

    let results = engine
        .execute_sql(&session, "SELECT tags FROM t WHERE id = 1")
        .expect("select");

    match &results[0] {
        StatementResult::Query { rows, .. } => {
            assert_eq!(rows.len(), 1);
            assert_eq!(
                rows[0].values[0],
                Value::Array(vec![
                    Value::Text("hello".to_owned()),
                    Value::Text("world".to_owned())
                ])
            );
        }
        other => panic!("expected query, got {other:?}"),
    }
}

#[test]
fn insert_char_and_varchar_array_columns_apply_typmods() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (f CHAR(5)[], g VARCHAR(5)[])")
        .expect("create table");

    engine
        .execute_sql(
            &session,
            "INSERT INTO t VALUES ('{\"abc\",\"abcde\"}', '{\"abc\",\"abcde\"}')",
        )
        .expect("insert arrays with text typmods");

    let rows = query_rows(&engine, &session, "SELECT f, g FROM t");
    assert_eq!(rows.len(), 1);
    assert_eq!(
        rows[0].values[0],
        Value::Array(vec![
            Value::Text("abc  ".to_owned()),
            Value::Text("abcde".to_owned()),
        ])
    );
    assert_eq!(
        rows[0].values[1],
        Value::Array(vec![
            Value::Text("abc".to_owned()),
            Value::Text("abcde".to_owned()),
        ])
    );
}

#[test]
fn insert_char_array_column_rejects_too_long_value() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (f CHAR(5)[])")
        .expect("create table");

    let err = engine
        .execute_sql(&session, "INSERT INTO t VALUES ('{\"too long\"}')")
        .expect_err("too-long char array element should fail");

    assert!(
        format!("{err}").contains("value too long for type character(5)"),
        "unexpected error: {err}"
    );

    let rows = query_rows(&engine, &session, "SELECT f FROM t");
    assert!(rows.is_empty(), "failing insert should not write a row");
}

#[test]
fn insert_array_element_target_list_builds_array() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (id INT NOT NULL, vals INT[])")
        .expect("create table");

    engine
        .execute_sql(
            &session,
            "INSERT INTO t (id, vals[2], vals[3]) VALUES (1, 20, 30)",
        )
        .expect("insert subscripted array targets");

    let results = engine
        .execute_sql(&session, "SELECT vals FROM t WHERE id = 1")
        .expect("select");

    match &results[0] {
        StatementResult::Query { rows, .. } => {
            assert_eq!(rows.len(), 1);
            assert_eq!(rows[0].values[0], Value::Text("[2:3]={20,30}".to_owned()));
        }
        other => panic!("expected query, got {other:?}"),
    }
}

#[test]
fn insert_array_index_target_type_mismatch_errors() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (vals INT[])")
        .expect("create table");

    let err = engine
        .execute_sql(&session, "INSERT INTO t (vals[2]) VALUES(now())")
        .expect_err("index target type mismatch should fail");

    assert!(
        format!("{err}").contains(
            "subscripted assignment to \"vals\" requires type integer but expression is of type timestamp with time zone"
        ),
        "unexpected error: {err}"
    );
}

#[test]
fn insert_array_slice_target_type_mismatch_errors() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (vals INT[])")
        .expect("create table");

    let err = engine
        .execute_sql(&session, "INSERT INTO t (vals[1:2]) VALUES(now())")
        .expect_err("slice target type mismatch should fail");

    assert!(
        format!("{err}").contains(
            "subscripted assignment to \"vals\" requires type integer[] but expression is of type timestamp with time zone"
        ),
        "unexpected error: {err}"
    );
}

#[test]
fn insert_array_slice_target_accepts_lower_dimensional_array_literal() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (vals INT[][][])")
        .expect("create table");

    engine
        .execute_sql(&session, "INSERT INTO t (vals[1:2]) VALUES ('{3,4}')")
        .expect("slice target should accept 1d array literal");

    let results = engine
        .execute_sql(&session, "SELECT vals FROM t")
        .expect("select");

    match &results[0] {
        StatementResult::Query { rows, .. } => {
            assert_eq!(rows.len(), 1);
            assert_eq!(
                rows[0].values[0],
                Value::Array(vec![Value::Int(3), Value::Int(4)])
            );
        }
        other => panic!("expected query, got {other:?}"),
    }
}

#[test]
fn insert_array_slice_target_with_huge_zero_lower_bound_rejects_program_limit() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (id INT PRIMARY KEY, vals INT[])")
        .expect("create table");

    let err = engine
        .execute_sql(
            &session,
            "INSERT INTO t (id, vals[0:2147483647]) VALUES (1, '{}')",
        )
        .expect_err("huge zero-based slice target should fail");

    assert_eq!(err.sqlstate(), aiondb_core::SqlState::ProgramLimitExceeded);
    assert!(
        format!("{err}").contains("too many elements"),
        "unexpected error: {err}"
    );
}

#[test]
fn insert_array_slice_target_with_huge_negative_lower_bound_rejects_program_limit() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (id INT PRIMARY KEY, vals INT[])")
        .expect("create table");

    let err = engine
        .execute_sql(
            &session,
            "INSERT INTO t (id, vals[-2147483648:2147483647]) VALUES (1, '{}')",
        )
        .expect_err("huge negative lower-bound slice target should fail");

    assert_eq!(err.sqlstate(), aiondb_core::SqlState::ProgramLimitExceeded);
    assert!(
        format!("{err}").contains("too many elements"),
        "unexpected error: {err}"
    );
}

#[test]
fn on_conflict_array_assignments_use_excluded_array_elements() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE arr_pk_tbl (pk INT PRIMARY KEY, f1 INT[])",
        )
        .expect("create table");
    engine
        .execute_sql(&session, "INSERT INTO arr_pk_tbl VALUES (1, '{1,2,3}')")
        .expect("seed table");

    let rows = query_rows(
        &engine,
        &session,
        "insert into arr_pk_tbl values (1, '{3,4,5}') \
         on conflict (pk) do update set \
         f1[1] = excluded.f1[1], \
         f1[3] = excluded.f1[3] \
         returning pk, f1",
    );

    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0].values[0], Value::Int(1));
    assert_eq!(
        rows[0].values[1],
        Value::Array(vec![Value::Int(3), Value::Int(2), Value::Int(5)])
    );
}

#[test]
fn on_conflict_array_assignments_preserve_nulls_from_excluded_slice_target() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE arr_pk_tbl (pk INT PRIMARY KEY, f1 INT[])",
        )
        .expect("create table");
    engine
        .execute_sql(&session, "INSERT INTO arr_pk_tbl VALUES (1, '{1,2,3}')")
        .expect("seed table");

    let rows = query_rows(
        &engine,
        &session,
        "insert into arr_pk_tbl(pk, f1[1:2]) values (1, '{6,7,8}') \
         on conflict (pk) do update set \
         f1[1] = excluded.f1[1], \
         f1[2] = excluded.f1[2], \
         f1[3] = excluded.f1[3] \
         returning pk, f1",
    );

    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0].values[0], Value::Int(1));
    assert_eq!(
        rows[0].values[1],
        Value::Array(vec![Value::Int(6), Value::Int(7), Value::Null])
    );
}

#[test]
fn interval_array_literal_coerces_elements_to_interval_values() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "select '{0 second,@ 1 hour @ 42 minutes @ 20 seconds}'::interval[]",
    );

    assert_eq!(
        rows[0].values[0],
        Value::Array(vec![
            Value::Interval(aiondb_core::IntervalValue::new(0, 0, 0)),
            Value::Interval(aiondb_core::IntervalValue::new(0, 0, 6_140_000_000)),
        ])
    );
}

#[test]
fn pg_typeof_varchar_array_cast_preserves_character_varying_name() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "SELECT pg_typeof(ARRAY[['a','bc'],['def','hijk']]::text[]::varchar[])",
    );

    assert_eq!(rows.len(), 1);
    assert_eq!(
        rows[0].values[0],
        Value::Text("character varying[]".to_owned())
    );
}

#[test]
fn string_to_array_empty_string_with_delimiter_returns_empty_array() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(&engine, &session, "SELECT string_to_array('', '|')");

    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0].values[0], Value::Array(Vec::new()));
}

// ===================================================================
// SELECT with ARRAY expressions
// ===================================================================

#[test]
fn select_array_literal() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(&session, "SELECT ARRAY[1, 2, 3]")
        .expect("select array literal");

    match &results[0] {
        StatementResult::Query { rows, .. } => {
            assert_eq!(rows.len(), 1);
            assert_eq!(
                rows[0].values[0],
                Value::Array(vec![Value::Int(1), Value::Int(2), Value::Int(3)])
            );
        }
        other => panic!("expected query, got {other:?}"),
    }
}

#[test]
fn select_array_subquery_collects_rows_into_array() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "CREATE TABLE arrtest_f (f2 DOUBLE PRECISION); \
         INSERT INTO arrtest_f VALUES (1.5), (2.5), (3.5); \
         SELECT ARRAY(SELECT f2 FROM arrtest_f ORDER BY f2)",
    );

    assert_eq!(rows.len(), 1);
    assert_eq!(
        rows[0].values[0],
        Value::Array(vec![
            Value::Double(1.5),
            Value::Double(2.5),
            Value::Double(3.5),
        ])
    );
}

#[test]
fn select_empty_array_errors() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let err = engine
        .execute_sql(&session, "SELECT ARRAY[]")
        .expect_err("empty array should fail");
    assert!(
        format!("{err:?}").contains("empty array")
            || format!("{err:?}").contains("cannot determine type"),
        "error should mention empty array: {err:?}"
    );
}

#[test]
fn select_empty_array_reports_pg_hint() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let err = engine
        .execute_sql(&session, "SELECT ARRAY[]")
        .expect_err("empty array should fail");
    let report = err.report();

    assert_eq!(report.message, "cannot determine type of empty array");
    assert_eq!(
        report.client_hint.as_deref(),
        Some("Explicitly cast to the desired type, for example ARRAY[]::integer[].")
    );
    assert_eq!(report.position, Some(8));
}

#[test]
fn select_empty_array_with_explicit_cast_uses_target_type() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(&session, "SELECT ARRAY[]::TEXT[]")
        .expect("empty array cast should succeed");

    match &results[0] {
        StatementResult::Query { rows, .. } => {
            assert_eq!(rows.len(), 1);
            assert_eq!(rows[0].values[0], Value::Array(Vec::new()));
        }
        other => panic!("expected query, got {other:?}"),
    }
}

#[test]
fn pg_typeof_reports_final_array_cast_type() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "SELECT pg_typeof(ARRAY[1,2,3]::text[]::int[]::float8[])",
    );

    assert_eq!(rows.len(), 1);
    assert_eq!(
        rows[0].values,
        vec![Value::Text("double precision[]".to_owned())]
    );
}

#[test]
fn ordered_array_range_predicates_coerce_text_literals() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TEMP TABLE arr_tbl (f1 INT[] UNIQUE);
             INSERT INTO arr_tbl VALUES ('{1,2,3}');
             INSERT INTO arr_tbl VALUES ('{1,2}');
             INSERT INTO arr_tbl VALUES ('{2,3,4}');
             INSERT INTO arr_tbl VALUES ('{1,5,3}');
             INSERT INTO arr_tbl VALUES ('{1,2,10}');",
        )
        .expect("set up arr_tbl");

    let mut greater_rows: Vec<_> = query_rows(
        &engine,
        &session,
        "SELECT f1 FROM arr_tbl WHERE f1 > '{1,2,3}' AND f1 <= '{1,5,3}'",
    )
    .into_iter()
    .map(|row| row.values[0].to_string())
    .collect();
    greater_rows.sort();
    assert_eq!(
        greater_rows,
        vec!["{1,2,10}".to_owned(), "{1,5,3}".to_owned()]
    );

    let mut between_rows: Vec<_> = query_rows(
        &engine,
        &session,
        "SELECT f1 FROM arr_tbl WHERE f1 >= '{1,2,3}' AND f1 < '{1,5,3}'",
    )
    .into_iter()
    .map(|row| row.values[0].to_string())
    .collect();
    between_rows.sort();
    assert_eq!(
        between_rows,
        vec!["{1,2,10}".to_owned(), "{1,2,3}".to_owned()]
    );
}

#[test]
fn ordered_array_range_predicates_follow_index_order() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "CREATE TEMP TABLE arr_tbl (f1 INT[] UNIQUE);
         INSERT INTO arr_tbl VALUES ('{1,2,3}');
         INSERT INTO arr_tbl VALUES ('{1,2}');
         INSERT INTO arr_tbl VALUES ('{2,3,4}');
         INSERT INTO arr_tbl VALUES ('{1,5,3}');
         INSERT INTO arr_tbl VALUES ('{1,2,10}');
         SET enable_seqscan TO off;
         SET enable_bitmapscan TO off;
         SELECT f1 FROM arr_tbl WHERE f1 > '{1,2,3}' AND f1 <= '{1,5,3}';",
    );

    assert_eq!(rows.len(), 2);
    assert_eq!(
        rows[0].values,
        vec![Value::Array(vec![
            Value::Int(1),
            Value::Int(2),
            Value::Int(10),
        ])]
    );
    assert_eq!(
        rows[1].values,
        vec![Value::Array(vec![
            Value::Int(1),
            Value::Int(5),
            Value::Int(3),
        ])]
    );
}

#[test]
fn array_equality_matches_null_elements_like_postgres() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "CREATE TABLE t (seqno INT, i INT[]);
         INSERT INTO t VALUES (101, ARRAY[1]), (102, ARRAY[NULL]);
         SELECT seqno FROM t WHERE i = '{NULL}' ORDER BY seqno;",
    );

    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0].values, vec![Value::Int(102)]);
}

#[test]
fn string_to_table_in_from_expands_rows_and_applies_null_string() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "SELECT v, v IS NULL AS is_null \
         FROM string_to_table('1,2,*,4', ',', '*') AS g(v)",
    );

    assert_eq!(rows.len(), 4);
    assert_eq!(rows[0].values[0], Value::Text("1".to_owned()));
    assert_eq!(rows[0].values[1], Value::Boolean(false));
    assert_eq!(rows[1].values[0], Value::Text("2".to_owned()));
    assert_eq!(rows[1].values[1], Value::Boolean(false));
    assert_eq!(rows[2].values[0], Value::Null);
    assert_eq!(rows[2].values[1], Value::Boolean(true));
    assert_eq!(rows[3].values[0], Value::Text("4".to_owned()));
    assert_eq!(rows[3].values[1], Value::Boolean(false));
}

#[test]
fn string_to_table_null_input_returns_zero_rows() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "SELECT v, v IS NULL AS is_null FROM string_to_table(NULL, '|') AS g(v)",
    );

    assert!(rows.is_empty());
}

#[test]
fn array_agg_distinct_order_by_desc_sorts_arrays_descending() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "select array_agg(distinct ar order by ar desc) \
         from (select array[i / 2] from generate_series(1,10) a(i)) b(ar)",
    );

    assert_eq!(rows.len(), 1);
    assert_eq!(
        rows[0].values[0],
        Value::Array(vec![
            Value::Array(vec![Value::Int(5)]),
            Value::Array(vec![Value::Int(4)]),
            Value::Array(vec![Value::Int(3)]),
            Value::Array(vec![Value::Int(2)]),
            Value::Array(vec![Value::Int(1)]),
            Value::Array(vec![Value::Int(0)]),
        ])
    );
}

#[test]
fn array_agg_distinct_order_by_desc_keeps_array_agg_column_name() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "select array_agg(distinct ar order by ar desc) \
             from (select array[i / 2] from generate_series(1,10) a(i)) b(ar)",
        )
        .expect("query");

    match &results[0] {
        StatementResult::Query { columns, .. } => {
            assert_eq!(columns.len(), 1);
            assert_eq!(columns[0].name, "array_agg");
        }
        other => panic!("expected query, got {other:?}"),
    }
}

#[test]
fn user_defined_unnest1_in_from_expands_scalar_rows() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "CREATE OR REPLACE FUNCTION unnest1(anyarray) \
         RETURNS SETOF anyelement AS $$ \
         SELECT $1[s] FROM generate_subscripts($1,1) g(s); \
         $$ LANGUAGE sql IMMUTABLE; \
         SELECT * FROM unnest1(array[1,2,3]) ORDER BY 1",
    );

    assert_eq!(rows.len(), 3);
    assert_eq!(rows[0].values, vec![Value::Int(1)]);
    assert_eq!(rows[1].values, vec![Value::Int(2)]);
    assert_eq!(rows[2].values, vec![Value::Int(3)]);
}

#[test]
fn user_defined_unnest1_in_from_preserves_function_name_as_column_header() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "CREATE OR REPLACE FUNCTION unnest1(anyarray) \
             RETURNS SETOF anyelement AS $$ \
             SELECT $1[s] FROM generate_subscripts($1,1) g(s); \
             $$ LANGUAGE sql IMMUTABLE; \
             SELECT * FROM unnest1(array[1,2,3]) ORDER BY 1",
        )
        .expect("query");

    assert_eq!(results.len(), 2);
    match &results[1] {
        StatementResult::Query { columns, rows } => {
            assert_eq!(columns.len(), 1);
            assert_eq!(columns[0].name, "unnest1");
            assert_eq!(rows.len(), 3);
            assert_eq!(rows[0].values, vec![Value::Int(1)]);
            assert_eq!(rows[1].values, vec![Value::Int(2)]);
            assert_eq!(rows[2].values, vec![Value::Int(3)]);
        }
        other => panic!("expected Query, got {other:?}"),
    }
}

#[test]
fn user_defined_unnest2_in_from_flattens_two_dimensional_arrays() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "CREATE OR REPLACE FUNCTION unnest2(anyarray) \
         RETURNS SETOF anyelement AS $$ \
         SELECT $1[s1][s2] \
           FROM generate_subscripts($1,1) g1(s1), \
                generate_subscripts($1,2) g2(s2); \
         $$ LANGUAGE sql IMMUTABLE; \
         SELECT * FROM unnest2(array[[1,2,3],[4,5,6]]) ORDER BY 1",
    );

    assert_eq!(rows.len(), 6);
    for (index, row) in rows.iter().enumerate() {
        assert_eq!(row.values, vec![Value::Int((index + 1) as i32)]);
    }
}

#[test]
fn pg_input_error_info_in_from_returns_pg_style_record() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "SELECT * FROM pg_input_error_info('{1,zed}', 'integer[]')",
    );

    assert_eq!(rows.len(), 1);
    assert_eq!(
        rows[0].values.as_slice(),
        [
            Value::Text("invalid input syntax for type integer: \"zed\"".to_owned()),
            Value::Null,
            Value::Null,
            Value::Text("22P02".to_owned()),
        ]
    );
}

#[test]
fn array_fill_with_explicit_lower_bounds_preserves_bounds() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let rows = query_rows(
        &engine,
        &session,
        "SELECT array_fill(7, ARRAY[3,3], ARRAY[2,2])",
    );

    assert_eq!(rows.len(), 1);
    assert_eq!(
        rows[0].values[0],
        Value::Text("[2:4][2:4]={{7,7,7},{7,7,7},{7,7,7}}".to_owned())
    );
}

#[test]
fn array_fill_rejects_null_dimension_and_low_bound_arrays() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    for sql in [
        "SELECT array_fill(1, NULL, ARRAY[2,2])",
        "SELECT array_fill(1, ARRAY[2,2], NULL)",
    ] {
        let err = engine
            .execute_sql(&session, sql)
            .expect_err("NULL dimension/low-bound arrays should fail");
        assert_eq!(
            err.report().message,
            "dimension array or low bound array cannot be null"
        );
    }
}

#[test]
fn array_fill_rejects_mismatched_or_multidimensional_bounds() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let err = engine
        .execute_sql(&session, "SELECT array_fill(1, ARRAY[2,2], '{}')")
        .expect_err("mismatched low-bound vector should fail");
    assert_eq!(err.report().message, "wrong number of array subscripts");
    assert_eq!(
        err.report().client_detail.as_deref(),
        Some("Low bound array has different size than dimensions array.")
    );

    let err = engine
        .execute_sql(&session, "SELECT array_fill(1, ARRAY[[1,2],[3,4]])")
        .expect_err("multidimensional dimension vector should fail");
    assert_eq!(err.report().message, "wrong number of array subscripts");
    assert_eq!(
        err.report().client_detail.as_deref(),
        Some("Dimension array must be one dimensional.")
    );
}

// ===================================================================
// NULL handling in arrays
// ===================================================================

#[test]
fn array_with_null_elements() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(&session, "CREATE TABLE t (id INT NOT NULL, vals INT[])")
        .expect("create table");

    engine
        .execute_sql(&session, "INSERT INTO t VALUES (1, ARRAY[1, NULL, 3])")
        .expect("insert array with null");

    let results = engine
        .execute_sql(&session, "SELECT vals FROM t WHERE id = 1")
        .expect("select");

    match &results[0] {
        StatementResult::Query { rows, .. } => {
            assert_eq!(rows.len(), 1);
            assert_eq!(
                rows[0].values[0],
                Value::Array(vec![Value::Int(1), Value::Null, Value::Int(3)])
            );
        }
        other => panic!("expected query, got {other:?}"),
    }
}
