use super::*;

// ---------------------------------------------------------------------------
// CREATE TABLE with FOREIGN KEY -- basic acceptance
// ---------------------------------------------------------------------------

#[test]
fn create_table_with_foreign_key() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY, name TEXT); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT NOT NULL, \
             FOREIGN KEY (parent_id) REFERENCES parents(id))",
        )
        .expect("execute");

    assert_eq!(results.len(), 2);
    assert!(matches!(
        &results[0],
        StatementResult::Command { tag, .. } if tag == "CREATE TABLE"
    ));
    assert!(matches!(
        &results[1],
        StatementResult::Command { tag, .. } if tag == "CREATE TABLE"
    ));
}

// ---------------------------------------------------------------------------
// INSERT respects FK -- valid insert succeeds
// ---------------------------------------------------------------------------

#[test]
fn insert_with_valid_foreign_key() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY, name TEXT); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT NOT NULL, \
             FOREIGN KEY (parent_id) REFERENCES parents(id)); \
             INSERT INTO parents VALUES (1, 'alice'); \
             INSERT INTO children VALUES (10, 1)",
        )
        .expect("execute");

    assert_eq!(results.len(), 4);
    assert!(matches!(
        &results[3],
        StatementResult::Command { tag, rows_affected } if tag == "INSERT" && *rows_affected == 1
    ));
}

#[test]
fn insert_with_valid_foreign_key_in_non_default_database_via_public_alias() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (admin, _) = engine.startup(startup_params()).expect("startup admin");

    engine
        .execute_sql(&admin, "CREATE DATABASE fk_shadow")
        .expect("create shadow database");

    let mut shadow_params = startup_params();
    shadow_params.database = "fk_shadow".to_owned();
    let (shadow, _) = engine.startup(shadow_params).expect("startup shadow");

    engine
        .execute_sql(
            &shadow,
            "CREATE TABLE public.parents ( \
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
                 email TEXT NOT NULL UNIQUE, \
                 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP \
             ); \
             CREATE TABLE public.children ( \
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
                 parent_id INT NOT NULL REFERENCES public.parents(id), \
                 note TEXT NOT NULL \
             ); \
             INSERT INTO public.parents (email) VALUES ('alice@example.com'); \
             INSERT INTO public.children (parent_id, note) VALUES (1, 'ok')",
        )
        .expect("insert through public alias in non-default database");
}

#[test]
fn alter_table_add_foreign_key_in_non_default_database_via_public_alias() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (admin, _) = engine.startup(startup_params()).expect("startup admin");

    engine
        .execute_sql(&admin, "CREATE DATABASE fk_shadow_alter")
        .expect("create shadow database");

    let mut shadow_params = startup_params();
    shadow_params.database = "fk_shadow_alter".to_owned();
    let (shadow, _) = engine.startup(shadow_params).expect("startup shadow");

    engine
        .execute_sql(
            &shadow,
            "CREATE TABLE public.parents ( \
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
                 email TEXT NOT NULL UNIQUE, \
                 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP \
             ); \
             CREATE TABLE public.children ( \
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
                 parent_id INT NOT NULL, \
                 note TEXT NOT NULL \
             ); \
             ALTER TABLE public.children \
                 ADD CONSTRAINT children_parent_id_fkey \
                 FOREIGN KEY (parent_id) REFERENCES public.parents(id); \
             INSERT INTO public.parents (email) VALUES ('alice@example.com'); \
             INSERT INTO public.children (parent_id, note) VALUES (1, 'ok')",
        )
        .expect("alter-table FK insert through public alias in non-default database");
}

// ---------------------------------------------------------------------------
// INSERT violates FK -- referenced value does not exist
// ---------------------------------------------------------------------------

#[test]
fn insert_violates_foreign_key() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY, name TEXT); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT NOT NULL, \
             FOREIGN KEY (parent_id) REFERENCES parents(id)); \
             INSERT INTO parents VALUES (1, 'alice')",
        )
        .expect("setup");

    let err = engine
        .execute_sql(&session, "INSERT INTO children VALUES (10, 999)")
        .expect_err("should fail");

    let err_msg = format!("{err}");
    assert!(
        err_msg.contains("foreign key"),
        "error should mention foreign key: {err_msg}"
    );
}

// ---------------------------------------------------------------------------
// INSERT with NULL FK value -- should succeed (NULL satisfies FK)
// ---------------------------------------------------------------------------

#[test]
fn insert_null_foreign_key_succeeds() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY, name TEXT); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT, \
             FOREIGN KEY (parent_id) REFERENCES parents(id)); \
             INSERT INTO children VALUES (10, NULL)",
        )
        .expect("execute");

    assert_eq!(results.len(), 3);
    assert!(matches!(
        &results[2],
        StatementResult::Command { tag, rows_affected } if tag == "INSERT" && *rows_affected == 1
    ));
}

// ---------------------------------------------------------------------------
// DELETE RESTRICT -- cannot delete parent row referenced by child
// ---------------------------------------------------------------------------

#[test]
fn delete_parent_with_referencing_child_fails() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY, name TEXT); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT NOT NULL, \
             FOREIGN KEY (parent_id) REFERENCES parents(id)); \
             INSERT INTO parents VALUES (1, 'alice'); \
             INSERT INTO children VALUES (10, 1)",
        )
        .expect("setup");

    let err = engine
        .execute_sql(&session, "DELETE FROM parents WHERE id = 1")
        .expect_err("should fail");

    let err_msg = format!("{err}");
    assert!(
        err_msg.contains("foreign key"),
        "error should mention foreign key: {err_msg}"
    );
}

// ---------------------------------------------------------------------------
// DELETE succeeds when no child references the row
// ---------------------------------------------------------------------------

#[test]
fn delete_unreferenced_parent_succeeds() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY, name TEXT); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT NOT NULL, \
             FOREIGN KEY (parent_id) REFERENCES parents(id)); \
             INSERT INTO parents VALUES (1, 'alice'), (2, 'bob'); \
             INSERT INTO children VALUES (10, 1); \
             DELETE FROM parents WHERE id = 2",
        )
        .expect("execute");

    // CREATE TABLE x2, INSERT parents, INSERT children, DELETE parent #2
    assert_eq!(results.len(), 5);
    assert!(matches!(
        &results[4],
        StatementResult::Command { tag, rows_affected } if tag == "DELETE" && *rows_affected == 1
    ));
}

// ---------------------------------------------------------------------------
// UPDATE FK column -- valid update succeeds
// ---------------------------------------------------------------------------

#[test]
fn update_foreign_key_column_to_valid_value() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY, name TEXT); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT NOT NULL, \
             FOREIGN KEY (parent_id) REFERENCES parents(id)); \
             INSERT INTO parents VALUES (1, 'alice'), (2, 'bob'); \
             INSERT INTO children VALUES (10, 1); \
             UPDATE children SET parent_id = 2 WHERE id = 10",
        )
        .expect("execute");

    assert_eq!(results.len(), 5);
    assert!(matches!(
        &results[4],
        StatementResult::Command { tag, rows_affected } if tag == "UPDATE" && *rows_affected == 1
    ));
}

// ---------------------------------------------------------------------------
// UPDATE FK column -- invalid update fails
// ---------------------------------------------------------------------------

#[test]
fn update_foreign_key_column_to_invalid_value_fails() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY, name TEXT); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT NOT NULL, \
             FOREIGN KEY (parent_id) REFERENCES parents(id)); \
             INSERT INTO parents VALUES (1, 'alice'); \
             INSERT INTO children VALUES (10, 1)",
        )
        .expect("setup");

    let err = engine
        .execute_sql(
            &session,
            "UPDATE children SET parent_id = 999 WHERE id = 10",
        )
        .expect_err("should fail");

    let err_msg = format!("{err}");
    assert!(
        err_msg.contains("foreign key"),
        "error should mention foreign key: {err_msg}"
    );
}

// ---------------------------------------------------------------------------
// UPDATE parent PK -- should fail when child references old value
// ---------------------------------------------------------------------------

#[test]
fn update_referenced_parent_column_fails() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY, name TEXT); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT NOT NULL, \
             FOREIGN KEY (parent_id) REFERENCES parents(id)); \
             INSERT INTO parents VALUES (1, 'alice'); \
             INSERT INTO children VALUES (10, 1)",
        )
        .expect("setup");

    // Updating the parent name (non-FK column) should succeed
    let results = engine
        .execute_sql(&session, "UPDATE parents SET name = 'alice2' WHERE id = 1")
        .expect("non-FK update should succeed");

    assert!(matches!(
        &results[0],
        StatementResult::Command { tag, rows_affected } if tag == "UPDATE" && *rows_affected == 1
    ));
}

// ---------------------------------------------------------------------------
// Multiple FK columns (composite FK)
// ---------------------------------------------------------------------------

#[test]
fn composite_foreign_key_valid_insert() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (a INT NOT NULL, b INT NOT NULL, PRIMARY KEY (a, b)); \
             CREATE TABLE children (id INT NOT NULL, pa INT NOT NULL, pb INT NOT NULL, \
             FOREIGN KEY (pa, pb) REFERENCES parents(a, b)); \
             INSERT INTO parents VALUES (1, 2); \
             INSERT INTO children VALUES (10, 1, 2)",
        )
        .expect("execute");

    assert_eq!(results.len(), 4);
    assert!(matches!(
        &results[3],
        StatementResult::Command { tag, rows_affected } if tag == "INSERT" && *rows_affected == 1
    ));
}

#[test]
fn composite_foreign_key_invalid_insert() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (a INT NOT NULL, b INT NOT NULL, PRIMARY KEY (a, b)); \
             CREATE TABLE children (id INT NOT NULL, pa INT NOT NULL, pb INT NOT NULL, \
             FOREIGN KEY (pa, pb) REFERENCES parents(a, b)); \
             INSERT INTO parents VALUES (1, 2)",
        )
        .expect("setup");

    let err = engine
        .execute_sql(&session, "INSERT INTO children VALUES (10, 1, 999)")
        .expect_err("should fail");

    let err_msg = format!("{err}");
    assert!(
        err_msg.contains("foreign key"),
        "error should mention foreign key: {err_msg}"
    );
}

#[test]
fn foreign_key_without_explicit_reference_columns_uses_parent_primary_key() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (a INT NOT NULL, b INT NOT NULL, PRIMARY KEY (a, b)); \
             CREATE TABLE children (id INT NOT NULL, pa INT NOT NULL, pb INT NOT NULL, \
             FOREIGN KEY (pa, pb) REFERENCES parents); \
             INSERT INTO parents VALUES (1, 2)",
        )
        .expect("setup");

    let err = engine
        .execute_sql(&session, "INSERT INTO children VALUES (10, 1, 999)")
        .expect_err("should fail");

    assert!(format!("{err}").contains("foreign key"));
}

#[test]
fn composite_foreign_key_with_partial_null_succeeds_under_match_simple() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (a INT NOT NULL, b INT NOT NULL, PRIMARY KEY (a, b)); \
             CREATE TABLE children (id INT NOT NULL, pa INT, pb INT, \
             FOREIGN KEY (pa, pb) REFERENCES parents(a, b)); \
             INSERT INTO parents VALUES (1, 2); \
             INSERT INTO children VALUES (10, NULL, 2), (11, 1, NULL)",
        )
        .expect("execute");

    assert!(matches!(
        &results[3],
        StatementResult::Command { tag, rows_affected } if tag == "INSERT" && *rows_affected == 2
    ));
}

// ---------------------------------------------------------------------------
// Multiple inserts in batch -- first valid, second violates FK
// ---------------------------------------------------------------------------

#[test]
fn batch_insert_second_row_violates_fk() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    engine
        .execute_sql(
            &session,
            "CREATE TABLE parents (id INT NOT NULL PRIMARY KEY); \
             CREATE TABLE children (id INT NOT NULL, parent_id INT NOT NULL, \
             FOREIGN KEY (parent_id) REFERENCES parents(id)); \
             INSERT INTO parents VALUES (1)",
        )
        .expect("setup");

    let err = engine
        .execute_sql(&session, "INSERT INTO children VALUES (1, 1), (2, 999)")
        .expect_err("should fail on second row");

    let err_msg = format!("{err}");
    assert!(
        err_msg.contains("foreign key"),
        "error should mention foreign key: {err_msg}"
    );
}

// ---------------------------------------------------------------------------
// Table with no FK -- DML should work normally (no overhead)
// ---------------------------------------------------------------------------

#[test]
fn table_without_fk_insert_delete_update() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let results = engine
        .execute_sql(
            &session,
            "CREATE TABLE t (id INT NOT NULL, val TEXT); \
             INSERT INTO t VALUES (1, 'a'), (2, 'b'); \
             UPDATE t SET val = 'c' WHERE id = 1; \
             DELETE FROM t WHERE id = 2; \
             SELECT id, val FROM t",
        )
        .expect("execute");

    assert_eq!(results.len(), 5);
    assert!(matches!(
        &results[4],
        StatementResult::Query { rows, .. } if rows.len() == 1
    ));
}

// ---------------------------------------------------------------------------
// pg_regress foreign_key.sql first block: inline REFERENCES, MATCH FULL,
// ON DELETE CASCADE, ON UPDATE CASCADE, no explicit ref column list.
// ---------------------------------------------------------------------------

#[test]
fn pg_regress_runner_with_explicit_catalog_store_keeps_inserts() {
    use std::sync::Arc;
    let catalog = Arc::new(aiondb_catalog_store::CatalogStore::new());
    let storage = Arc::new(aiondb_storage_engine::InMemoryStorage::new_without_wal());
    let engine = EngineBuilder::for_testing()
        .with_catalog_txn(catalog.clone())
        .with_catalog_reader(catalog.clone())
        .with_catalog_writer(catalog.clone())
        .with_sequence_manager(catalog)
        .with_storage_ddl(storage.clone())
        .with_storage_dml(storage.clone())
        .with_storage_txn(storage)
        .build()
        .unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let stmts = [
        "CREATE TABLE PKTABLE ( ptest1 int PRIMARY KEY, ptest2 text );",
        "CREATE TABLE FKTABLE ( ftest1 int REFERENCES PKTABLE MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE, ftest2 int );",
        "INSERT INTO PKTABLE VALUES (1, 'Test1');",
        "INSERT INTO PKTABLE VALUES (2, 'Test2');",
        "INSERT INTO FKTABLE VALUES (1, 2);",
        "INSERT INTO FKTABLE VALUES (2, 3);",
        "INSERT INTO FKTABLE VALUES (NULL, 1);",
    ];
    for s in stmts {
        engine
            .execute_sql(&session, s)
            .unwrap_or_else(|e| panic!("stmt {s}: {e}"));
    }

    let bad = engine.execute_sql(&session, "INSERT INTO FKTABLE VALUES (100, 2);");
    assert!(bad.is_err(), "fk violation expected");

    if engine.has_active_transaction(&session).unwrap_or(false) {
        let _ = engine.execute_sql(&session, "ROLLBACK");
    }

    let rows_q = engine
        .execute_sql(&session, "SELECT count(*)::int FROM fktable;")
        .expect("count");
    if let StatementResult::Query { rows, .. } = &rows_q[0] {
        let n = rows[0].values[0].to_string();
        assert_eq!(
            n, "3",
            "expected 3 rows after failed insert + rollback, got {n}"
        );
    } else {
        panic!("expected Query result");
    }
}

#[test]
fn pg_regress_runner_ish_flow_keeps_inserts_after_failed_insert() {
    // Mirrors the pg-regress runner: each statement is its own
    // execute_sql call, and after a failed statement the runner issues an
    // implicit ROLLBACK if a transaction is still active. PG's autocommit
    // means the prior successful inserts must remain after that rollback.
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let stmts = [
        "CREATE TABLE PKTABLE ( ptest1 int PRIMARY KEY, ptest2 text );",
        "CREATE TABLE FKTABLE ( ftest1 int REFERENCES PKTABLE MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE, ftest2 int );",
        "INSERT INTO PKTABLE VALUES (1, 'Test1');",
        "INSERT INTO PKTABLE VALUES (2, 'Test2');",
        "INSERT INTO FKTABLE VALUES (1, 2);",
        "INSERT INTO FKTABLE VALUES (2, 3);",
        "INSERT INTO FKTABLE VALUES (NULL, 1);",
    ];
    for s in stmts {
        engine
            .execute_sql(&session, s)
            .unwrap_or_else(|e| panic!("stmt {s}: {e}"));
    }

    let bad = engine.execute_sql(&session, "INSERT INTO FKTABLE VALUES (100, 2);");
    assert!(bad.is_err(), "fk violation expected");

    // Runner-style: implicit rollback if a tx is still active.
    if engine.has_active_transaction(&session).unwrap_or(false) {
        let _ = engine.execute_sql(&session, "ROLLBACK");
    }

    let rows_q = engine
        .execute_sql(&session, "SELECT count(*)::int FROM fktable;")
        .expect("count");
    if let StatementResult::Query { rows, .. } = &rows_q[0] {
        let n = rows[0].values[0].to_string();
        assert_eq!(
            n, "3",
            "expected 3 rows after failed insert + rollback, got {n}"
        );
    } else {
        panic!("expected Query result");
    }
}

#[test]
fn pg_regress_first_block_inline_match_full_cascade() {
    let engine = EngineBuilder::for_testing().build().unwrap();
    let (session, _) = engine.startup(startup_params()).expect("startup");

    let stmts = [
        "CREATE TABLE PKTABLE ( ptest1 int PRIMARY KEY, ptest2 text );",
        "CREATE TABLE FKTABLE ( ftest1 int REFERENCES PKTABLE MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE, ftest2 int );",
        "INSERT INTO PKTABLE VALUES (1, 'Test1');",
        "INSERT INTO PKTABLE VALUES (2, 'Test2');",
        "INSERT INTO PKTABLE VALUES (3, 'Test3');",
        "INSERT INTO PKTABLE VALUES (4, 'Test4');",
        "INSERT INTO PKTABLE VALUES (5, 'Test5');",
        "INSERT INTO FKTABLE VALUES (1, 2);",
        "INSERT INTO FKTABLE VALUES (2, 3);",
        "INSERT INTO FKTABLE VALUES (3, 4);",
        "INSERT INTO FKTABLE VALUES (NULL, 1);",
    ];
    for s in stmts {
        let r = engine.execute_sql(&session, s);
        assert!(r.is_ok(), "stmt failed [{s}]: {:?}", r.err());
    }

    let bad = engine.execute_sql(&session, "INSERT INTO FKTABLE VALUES (100, 2);");
    assert!(bad.is_err(), "fk violation expected, got {bad:?}");

    let rows_q = engine
        .execute_sql(&session, "SELECT count(*)::int FROM fktable;")
        .expect("count");
    if let StatementResult::Query { rows, .. } = &rows_q[0] {
        assert_eq!(rows.len(), 1);
        let n = rows[0].values[0].to_string();
        assert_eq!(n, "4", "expected 4 rows in fktable, got {n}");
    } else {
        panic!("expected Query result");
    }
}
